yt-project/unyt

docs/usage.rst, unyt/__init__.py, unyt/array.py, unyt/equivalencies.py, unyt/tests/test_unit_systems.py, unyt/tests/test_unyt_array.py, unyt/unit_object.py, unyt/unit_symbols.py
This makes `unyt` behave more like astropy.units: the unit objects importable from the top-level `unyt` namespace become `Unit` objects, not `unyt_quantity` instances. The physical constants in `unyt.physical_constants` that are also in the top-level `unyt` namespace remain quantities. 
This change reduces the overhead of doing something like:
```python
from unyt import g
[1, 2, 3]*g
```
by as much as a factor of 4.
Unfortunately this change also triggers a number of other changes to tests (mostly in examples that import something directly from unyt and use it as a quantity or an array). I'm not sure whether that's something we should worry about given that the most common use cases continue to work and most of the examples in the tests are toy examples.
=> make objects in unyt.unit_objects Unit instances

unyt/array.py, unyt/unit_object.py, unyt/unit_registry.py
This fixes some performance regressions due to recent code churn. I've restored what we used to call `UnitRegistry.unit_objs`. It's now called `UnitRegistry._unit_object_cache`. This makes it clearer that it's a private implementation detail and that it's a cache.
I've additionally made `_check_em_conversion` a pure function that accepts sympy expressions and returns a tuple containing a string and a float. This allows me to decorate it with lru_cache, which saves additional time when converting units.
=> Convert speedup

setup.py
This line in our setup.py causes issues on conda-forge. Let's remove it since I don't think we need it and setup_requires is a footgun because it uses setuptools to install stuff.
=> remove setup_requires

unyt/array.py, unyt/tests/test_unyt_array.py
This allows one to do something like:
```
data = unyt_array([1, 2, 3], '')
3**data
```
This is a well-defined operation that we weren't allowing before. With this PR it's once again legal to do this.
This came up in the context of porting yt to use unyt under the hood.
=> Allow taking scalars to dimensionless array powers

unyt/array.py, unyt/tests/test_units.py, unyt/unit_object.py
This PR refactors the CGS <-> MKS conversions to be based around dimensions. This makes it possible to convert code magnetic units between unit systems (or any unit that has the same dimensions as gauss or tesla).
This fixes issues with converting code E&M magnetic units between unit systems and I've added a test to capture this use case.
This came up in the context of getting yt to use unyt under the hood.
=> Use dimensions of units to do CGS <-> MKS conversions.

docs/usage.rst, unyt/tests/test_unit_registry.py, unyt/unit_object.py, unyt/unit_registry.py
Closes #30 
I've also removed a yt-specific error message with the intention of adding special logic to catch and report that error in a version of yt that depends on unyt.
=> make UnitRegistry.__contains__ a bit smarter 

unyt/tests/test_unyt_array.py
It looks like numpy 1.15.0 caused some breakage on python2.7. It has something to do with array scalars not behaving correctly (the backtrace comes from a usage of `assert_equal`). I don't really want to dig and figure out exactly what changed, so I'm just papering it over here by dropping the problematic call to `assert_equal`.
=> paper over python2 test failure

docs/usage.rst, unyt/array.py, unyt/dimensions.py, unyt/equivalencies.py, unyt/tests/test_unyt_array.py, unyt/unit_object.py
I spoke to @ngoldbaum briefly at Scipy2018 about the spectral equivalence and the units my particular sector of spectroscopy uses. In particular we use wavenumbers  (1/cm) extensively.
This PR adds a spatial frequency dimension `1 / (length)`, and then makes the `spectral` equivalence able to convert to and from spatial_freqency units.
I considered adding `wn` as a unit (equivalent to `1/cm`), but concluded that would likely be better suited to my more specific packages. If the maintainers would like to add it, let me know, perfectly willing to submit such a PR.
=> Add Spatial frequency, with spectral equivalence support

docs/usage.rst, setup.cfg, unyt/array.py, unyt/exceptions.py, unyt/tests/test_unyt_array.py, unyt/unit_object.py, unyt/unit_registry.py
This responds to the suggestion from @ygrange in https://github.com/openjournals/joss-reviews/issues/809#issuecomment-406382226. Thanks so much for pointing this out! For some reason I decided to exclude the exception classes from the code coverage estimates, which was totally unnecessary. Adding docstrings allowed me to catch a few outright bugs or places where we should have been raising custom exceptions but weren't. It also allows me to expand the test coverage even more (cue evil laughter).
=> Add documentation for the exception classes in unyt

CONTRIBUTING.rst
This responds to @ygrange's comment here: https://github.com/openjournals/joss-reviews/issues/809#issuecomment-406381056
I've added a section to the developer docs on running the tests locally using either `py.test` or `tox`. I've also mentioned the extra test dependencies. I also expanded a little bit on the pull request guidelines to reflect what I actually think about merging PRs to this repo. @jzuhone might want to give this a quick lookover.
=> Add documentation on running the tests

appveyor.yml, unyt/array.py
There's a doctest in the docstring that should suffice as a test. Let's see what the coverage report says. ping @brittonsmith 
It turns out numpy has an internal hook to call obj.argsort if it's defined for an object passed to `np.argsort`. Not sure why this behaves differently in yt.units, in principle this could be backported there.
=> add unyt_array.argsort. Fixes #51

docs/usage.rst, tox.ini, unyt/_testing.py, unyt/array.py, unyt/equivalencies.py, unyt/exceptions.py, unyt/tests/test_unyt_array.py, unyt/unit_object.py, unyt/unit_registry.py, unyt/unit_symbols.py
Up to now we assumed pretty much everywhere that data are 64 bit floats or that data will eventually get converted to 64 bit floats. This led to weird behavior if people tried to use integer or reduced precision floats, see e.g. the array printing weirdness reported in #55.
My justification for not supporting ints was that data with units are "naturally" floats. However sometimes it's important for e.g. memory layout reasons to have data as ints but still track unit metadata. Perhaps more importantly for memory layout or memory size reasons it's also important to store data in 32 bit or 16 bit precision if that's OK for the kind of data that a person is working with.
This PR changes that behavior and makes it so that we infer the dtype of data using the same rules as `np.array` for data …
=> Support integer and reduced precision arrays. Fixes #55

docs/usage.rst, unyt/array.py, unyt/equivalencies.py, unyt/tests/test_units.py, unyt/tests/test_unyt_array.py, unyt/unit_object.py
This adds automatic simplification of units in the form of a new `Unit.simplify()` method. It also makes it so that products and quotients of arrays with units will now automatically be simplified.
Caveats:
* I haven't done any performance benchmarking. In principle calling `simplify()` in the `__array_ufunc__` machinery is "free" because it's behind an LRU cache but I need to actually verify that. There's also an extra multiplication on the array that happens if there's any unit cancellation. In practice though most people would be "manually" doing that simplification and therefore incurring the cost of the extra multiplication anyway. All that said I still need to actually verify that the performance impact is at least acceptable.
* My tests are not *super* extensive and this is an …
=> add automatic unit simplification. closes #49

unyt/tests/test_units.py, unyt/unit_object.py, unyt/unit_registry.py
closes #60 
@jzuhone if you could look at this that would be awesome.
There is a behavior change (see the changed test) but I think it's worth making the behavior change to avoid the obviously incorrect behavior in #60. In principle we could also fix #60 and avoid the behavior change by just removing the conversion between ohm and statohm from the `em_conversions` dictionary however the exact same problem could also happen for the other CGS EM units, just less often because they have more unusual dimensions that won't come up in a calculation as often. Better to just remove the possibility of the bug.
Thankfully we're about to do a 2.0 release so behavior changes like this are OK if they're worth it (although should be avoided if we possibly can).
=> fix incorrect conversions between inverse velocities and ohm. 

unyt/_unit_lookup_table.py, unyt/tests/test_units.py, unyt/unit_symbols.py
closes #34 
I tried to get this working on python2.7 and it was not worth the trouble. Works more less out of the box on python3 though so I've elected to simply make the feature python3-only. However to make the tests continue to pass on Python2.7 I had to implement this in a sort of boroque way (thus the use of `globals` and `getattr` to make sure I'm always referring to the new variables with unicode identifiers I've defined using strings).
=> add support for using unicode mu as the micro prefix.

docs/usage.rst, unyt/array.py, unyt/tests/test_unit_systems.py, unyt/tests/test_units.py, unyt/unit_object.py, unyt/unit_registry.py, unyt/unit_systems.py
this required a fair amount of refactoring to avoid a circular dependency generated by the fact that the unit systems currently store Unit objects. That's not actually necessary, the unit systems only need to store the units that make up the system and can generate Unit objects to return to the user when `__getitem__` is called.
Now that unit registries are associated with a unit system, the registry can be used to determine the appropriate unit system to use for a calculation. This allows the unit system to be controlled by an application by making use of a custom unit registry. Calls to in_base or get_base_equivalent will return data in the appropriately configured unit system associated with that registry.
I haven't yet added configuration for unit systems, but this at least makes it …
=> give unit registries a unit system

.gitignore, setup.py
Since we have a pyproject.toml we opt into PEP 517/518 with the latest release of pip. One side effect is that the directory setup.py is run inside of is no longer on `sys.path`. We want that behavior though because that's how versioneer works.
Also add a gitignore rule for a new file pip is creating. According to the issue in the comment it looks like we'll probably be able to remove it after the next release of pip though.
=> fix path issues with new pip versions

unyt/tests/test_define_unit.py, unyt/unit_object.py
Previously feeding a tuple with a custom registry unit would err, which probably shouldn't. See this example:
```python
from unyt import UnitRegistry, define_unit
reg = UnitRegistry()
define_unit('code_length', (1, 'm'), registry=reg)
define_unit('code_area', (1, 'code_length**2'), registry=reg)
```
It would result in `unyt.exceptions.UnitParseError: Could not find unit symbol 'code_length' in the provided symbols.` without this patch.
=> Improve define_unit consistency with a custom registry

docs/usage.rst, unyt/array.py, unyt/physical_constants.py, unyt/unit_object.py, unyt/unit_symbols.py, unyt/unit_systems.py
This adds two new functions, `add_symbols` and `add_constants` to the public namespace, adds tests, and documents them. It also adds some extra documentation about how library authors can deal with custom unit systems now that #62 is merged. Finally I noticed some minor doc issues (e.g. formatting problems as well as some minor organizational issues) that I've also fixed. I tried to keep my commits atomic so reviewing commit-by-commit might be easier than looking at the PR diff.
=> Tools and docs for authors writing libraries wrapping unyt

unyt/array.py, unyt/tests/test_unyt_array.py
This fixes an issue @cphyc spotted in yt in https://github.com/yt-project/yt/pull/2204. It's still an issue here so I've taken his fix and made it so it applies to unyt as well. It looks like we also dropped some tests for vstack which were in yt at some point so I've added those back.
=> add missing axis argument to np.stack call in ustack

unyt/_unit_lookup_table.py
This makes it so the names "rsun", "lsun", and "au" show up as valid units since those names are used by yt.
=> add some missing alternate spellings

.travis.yml, CONTRIBUTING.rst, appveyor.yml
It turns out tox supports running tests in parallel. This should make the tests run a bit faster so let's do that.
=> run tests in parallel

unyt/unit_object.py
It turns out that automatic unit simplification can cause a small amount of deviation in base values between the units of an expression constructed via some complicated algebraic expression. This showed up in yt in the context of computing the standard deviation of a derived quantity. The unit's dimensions ended up correct, but the `base_value` ended up very slightly different from the `base_value` of the original unit.
This papers over that issue by allowing a very small degree of difference between the `base_value` of two equivalent units while still passing `==` equality.
This may be a dubious choice. It wasn't necessary for yt.units because we weren't doing as many floating point operations creating new unit objects whenever we multiplied or divided two arrays, although I think in …
=> allow for floating point slop in base values when comparing units

docs/usage.rst, unyt/tests/test_unit_systems.py, unyt/unit_registry.py, unyt/unit_systems.py
This fixes some issues I found trying to get unyt working with yt. First, it adds an explicit test for a code unit system like yt's. It also makes sure that custom units will show up in a unit container object like i've created in yt via `ds.units`, to make sure that things like `ds.units.code_length` will work as expected. I also added a new `has_current_mks` property on the `UnitSystem` class that I found useful in the process of getting yt working with unyt.
=> fix issues working with code units

unyt/array.py, unyt/tests/test_unyt_array.py
I didn't add an `__imatmul__` implementation because that's not supported by upstream numpy yet.
=> add a matmul implementation. fixes #75

unyt/tests/test_unit_registry.py, unyt/tests/test_units.py, unyt/unit_registry.py
We use "is" equality in a bunch of places when comparing dimensions. This is problematic given the current approach for the json saving and loading functionality, since `sympify` will generate distinct `Symbol` objects. We could replace the `is` equality uses with `==`, but that is anywhere from a few times to 50 times slower:
```
In [13]: from unyt.dimensions import length, energy
In [14]: %timeit length is length
34.8 ns ± 0.326 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [15]: %timeit length == length
128 ns ± 6.87 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [16]: %timeit length is not energy
39.8 ns ± 5.37 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [17]: %timeit length == energy
2.38 µs ± 155 ns per loop (mean ± std. dev. …
```
=> populate dimensions for restored json unit registries from dimensions namespace

.travis.yml, CONTRIBUTING.rst, tox.ini, unyt/_parsing.py, unyt/array.py, unyt/exceptions.py, unyt/tests/test_units.py, unyt/tests/test_unyt_array.py, unyt/unit_object.py, unyt/unit_symbols.py, unyt/unit_systems.py
This includes fixes for several performance issues I found integrating unyt with yt.
Big changes are refactoring of parsing into a new `unyt._parsing` private module, which allows me to refactor the `UnitSystem` class to parse unit names and store unit expressions internally, a big performance win since we can avoid repeatedly and expensively parsing unit strings whenever we go through the unit system machinery.
This also includes a small behavior change in the cgs/mks conversion rules to make them slightly more relaxed. This leads to a big performance wins for all unit conversions so I definitely think it's worth it, see the test changes for the extent of the changes.
Last there are a few other more minor or isolated changes that were all clear-cut performance wins and didn't lead to any …
=> Performance improvements

docs/index.rst, docs/usage.rst, unyt/_physical_ratios.py, unyt/equivalencies.py, unyt/physical_constants.py, unyt/tests/test_unyt_array.py, unyt/unit_systems.py
See https://physics.nist.gov/cgi-bin/cuu/Value?bg
Assuming [this table on wikipedia is correct](https://en.wikipedia.org/wiki/Gravitational_constant#Modern_value), we are currently using the 2010 CODATA value. Let's update this to use the 2014 CODATA value.
=> update value of newton's constant to 2014 CODATA value. Closes #83.

docs/requirements.txt, docs/usage.rst
This fixes some minor style and formatting issues in the docs. I'm pinning the sphinx version to work around https://github.com/sphinx-doc/sphinx/issues/6545 which I've reported upstream.
=> Minor style fixes, pin sphinx version

unyt/array.py, unyt/tests/test_unyt_array.py, unyt/unit_object.py
Before this PR the following script:
```python
import unyt as u
d = 12.0*u.Gauss
print(d.in_cgs().units)
```
would print `'T'`.
We need extra logic to check if we've been asked to convert to a new unit system or not. If not then we shouldn't do the EM conversion at all.
This fixes the broken test in my yt pull request that adds support for unyt.
=> ensure EM conversions only happen when we want to change unit systems

benchmarks/bench.py
I couldn't find a package for perf on pypi, but I found [pyperf](https://github.com/vstinner/pyperf), which seems to have the same API as the perf library that was used in bench.py.
=> Add python-quantities to list of tested libraries in bench.py

unyt/array.py, unyt/tests/test_unyt_array.py
The clip function in yt master is causing issues when called from within the ytdata frontend.  This test seems to be the smallest way I can reproduce it.  However, I can only make it fail on appveyor.  I'm optimistic that issuing this pull-request will help track down why it's problematic, and where the (platform specific?) failure occurs.
=> Adding a test that fails for yt on appveyor.

unyt/array.py, unyt/tests/test_unyt_array.py
Up until now we were unconditionally raising a UnitOperationError for all
comparisons of data with different units, including `equal` and `not_equal`. Due
to details of how NumPy handles this internally (I guess it happens in C code
because I don't see any of this when stepping through in pdb) numpy swallows
that error and raises a DeprecationWarning (!?) causing confusing behavior when
comparing quantities with units that are not dimensionally equivalent.
The fix is to add special handling for equal and not_equal when comparing data
with units that have different dimensions. I've also added tests for this case.
This may have negative performance implications for some workflows however I
think we have to do this in the interest of correctness. Also comparing data
with different units like …
=> Allow == and != for data with different units. Fixes #105.

unyt/array.py, unyt/exceptions.py, unyt/unit_object.py
Before:
```
In [2]: %timeit 3 * u.g
4.6 µs ± 56.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
After:
```
In [3]: %timeit 3 * u.g
2.94 µs ± 47.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
So about 35% faster!
I'm getting rid of `UnitDtypeError` because it wasn't tested beyond the
docstring for `UnitDtypeError` itself and `UnitOperationError` is just as
easy to understand.
I also added `__slots__` both to speed up attribute access as well as to improve
memory footprint.
`ImportCache` is needed because the caching trick won't work on the class itself because `__slots__` is defined so now I just create a singleton to hold the cache.
ping @thisch
=> simplify creating arrays and quantities with units

unyt/tests/test_units.py, unyt/unit_object.py
I discovered that the `__hash__` implementation for `Unit` is incorrect when looking at a perf bottleneck in some code; things were slowing down because the `@lru_cache` on `_multiply_units` was very rarely being hit.
The Python docs say:
> Objects which are instances of user-defined classes are hashable by default. They all compare unequal (except with themselves), and their hash value is derived from their id().
The previous implementation which just forwarded to the default hash would vary based on the `id()` of the object, and thus the `@lru_cache` would always miss.
I'm not entirely sure this implementation is correct. This is what I invented late last night, but it looks a bit unlike the `__eq__`, but my guess at a test cast that would prove this incorrect isn't failing.
=> Fix unit hash function

.travis.yml, docs/usage.rst, tox.ini, unyt/_parsing.py, unyt/array.py, unyt/tests/test_unyt_array.py, unyt/unit_object.py
This fixes a number of issues caused by updates to upstream libraries we depend on. This is a bit of a grab-bag PR that makes the tests pass again on the latest versions of our dependencies. Unfortunately I can't easily issue these changes as separate PRs since the tests will be broken without all of these coming in at once. If you have questions about reviewing this I'm happy to help out.
To catch issues caused by upstream changes more quickly in the future I've updated the tox config to always recreate a virtualenv. This will ensure we get test failures on the cron job test whenever an upstream release breaks our test suite.
I also made the following updates to our tox config:
* Add testing for python 3.8, update older python minor versions
* Remove pytest version constraint now that …
=> Add support for latest versions of h5py, sympy, numpy, and pytest 

unyt/unit_object.py
This implements the correction to the hash function change from #114 I discussed [here](https://github.com/yt-project/unyt/pull/114#issuecomment-569844465).
=> correct unit hash computation to use unit registry hash data

unyt/unit_registry.py
We have a code that does some analysis on snapshots then dumps HDF5 files which serialize a bunch of unyt_arrays and unyt_quantities. It also serializes the unit system that was created when the snapshot was opened. So when someone wants to loop over hundreds of these files which contain serialized unyt structures, the process overall is dominated by reconstituting the serialized unit registry for each file.
The `functools.lru_cache` can't be keyed on both the arguments to the `sympify` call, because the second argument is not hashable. I think this is okay because modifying the module seems like it would invalidate other things as well.
=> Try to speed up UnitRegistry.from_json

docs/usage.rst, tox.ini, unyt/mpl_interface.py, unyt/tests/test_mpl_interface.py
This supplements #122 from @l-johnston, adding support for matplotlib 2.2.4 and refactoring a little so everything works on both versions.
=> add support for matplotlib 2.2.4

unyt/array.py, unyt/unit_registry.py
Fixes #136.
I tried to add a test for this but since triggering this requires having yt-4.0 installed I've punted on adding the test for now. It might be easier to add the test in yt's test suite.
Using the example from Kacper's comment in #136:
```
In [1]: import shelve
...: dd = shelve.open("py35_local_flash_009")
...: run = dd["sloshing_low_res_hdf5_plt_cnt_0300"]
...: le = run["GridHierarchy_sloshing_low_res_hdf5_plt_cnt_0300_all"]["grid_left_edges"][0]
In [2]: le.units.registry['cm']
Out[2]: (0.01, (length), 0.0, '\\rm{cm}', False)
In [3]: le.units.base_value
Out[3]: 0.01
```
Before this PR the `base_value` of `le.units` is incorrectly read in as `1.0`.
=> correct unit registries saved as pickles by yt.units

unyt/array.py, unyt/tests/test_unit_registry.py, unyt/tests/test_unyt_array.py, unyt/unit_registry.py
The addition of `name` to the `__new__` signature broke existing subclasses(like yt's `ImageArray`) that don't have `name` in their `__new__` signature. As a bandaid I've wrapped the places `__new__` gets called in try/except blocks.
I also fixed a logic error that caused custom units to not be loaded correctly from jsons or pickles.
I've added tests that would catch both of these issues so hopefully we won't have future recurrances of these regressions.
It may make sense to run a test job that runs the yt unit tests since it seems to be able to find more bugs thant he unyt tests alone.
ping @l-johnston for the changes to how `name` works - maybe there's a better way than try/except?
=> Fix bugs spotted by the yt tests

tox.ini
@ngoldbaum I added a conditional line in the tox configuration to run the unyt.test() function for python3.8 (https://tox.readthedocs.io/en/latest/config.html#factors). It seems to work fine on my local environment.
=> Adding optional line in tox for python 3.8

HISTORY.rst, tox.ini, unyt/_unit_lookup_table.py, unyt/tests/test_units.py
This closes #145 .
This script:
```python
import yt
ds = yt.testing.fake_amr_ds(["density"])
p = yt.SlicePlot(ds, "x", "density")
p.set_axes_unit("um")
```
demonstrates the old and new behavior; first is old, second is new.
=> Switch from u00b5 to u03bc for micro

unyt/tests/test_unit_registry.py, unyt/unit_registry.py
This closes #157 by examining the old-style dimensions, and if they are *equal* but not *identical*, replacing them.  This allows them to match the dimensions checked in the unit registry later.
=> Replace dimensions that are equal but not identical.

unyt/array.py, unyt/tests/test_units.py
another go at https://github.com/yt-project/unyt/pull/163, and fix https://github.com/yt-project/yt/issues/874
I've added tests for both commutative and non-commutative operators. Two of them (`//` and `%`) are currently failing and I can't seem to understand why, could it be due to rounding errors ?
@jzuhone , do you have any clue ?
=> bugfix: fix commutativity in unyt_array operators

HISTORY.rst, setup.cfg, tox.ini, unyt/mpl_interface.py
* Fix compatibility with the newest black version (the docstring in `mpl_interface.py`).
* Drop python3.5 testing and support. Ultimately this is caused by `pytest-doctest-plus` dropping support for 3.5 and breaking. Python 3.5 is EOL so let's just drop support. We're probably going to need to drop support for python3.6 and add support for 3.9 soon but I'll deal with that later.
* Remove a line from `setup.cfg` that wasn't doing anything and that pytest was complaining about.
Once this is merged I'll tag 2.8.0 and do a release. I may need to do some more if there are test failures I didn't catch locally.
=> 2.8.0 fixes

docs/usage.rst, unyt/array.py, unyt/unit_object.py
This PR simply gets the CI passing (in local runs of `tox` and in GitHub Actions) so that PR #187 can proceed smoothly. It just applies Black to the code base to take care of the space differences that [Black `v21.4b0+` now enforces](https://black.readthedocs.io/en/stable/change_log.html#id6) and then in the docs adds in a missing import of `unt_array` and then adds a write option to a `h5py.File` call (perhaps a somewhat recent change in `h5py`?).
I don't think that `yt` does squash and merge commits like I usually do, but if that _is_ something that happens
**Suggested squash and merge commit message**
```
* Apply Black to codebase to revise docstring whitespace
- Black v21.4b0 release notes: Black now processes one-line docstrings by stripping leading and trailing spaces, and adding a …
```
=> fix: Apply Black and update usage docs code

AUTHORS.rst, docs/usage.rst, unyt/array.py, unyt/tests/test_unyt_array.py
This adds a from_string method to the unyt_quantity class. I originally wrote it in a separate project where I need to parse quantities from configuration (text) files, then realized it would be useful to have it as part of the library.
I consider this a draft for now. The implementation works as intended in every case I could think of (valid as well as invalid ones), but I would like to add doc strings (w/ doctests) to the actual function.
=> FEAT: implement unyt.unyt_quantity.from_string

unyt/mpl_interface.py, unyt/tests/test_mpl_interface.py
Fixes #179 by handling the case where a tuple is passed to `default_units` (which occurs when the plots is empty and a limit call is made). I've also added a test.
Perhaps @l-johnston would like to take a look at this.
=> Fix #179 by handling matplotlib case for limits

unyt/tests/test_unyt_array.py
This avoids leaving a file behind in the directory the tests are run in.
=> use a temporary file in test_complexvalued

unyt/array.py, unyt/exceptions.py, unyt/tests/test_unyt_array.py
Fixes #210.
See the test I modified for a usage example.
=> support coercing iterables with nonuniform dimensionally equivalent units to a single unyt_array

README.rst
a quick follow up to #209: adding a badge for the new workflow would make problems visible to more people than the ones that get notified (still not sure who it's supposed to be).
Other than that I report that the workflow looks like it's doing it's job so far :)
See my fork for rendering
https://github.com/neutrinoceros/unyt/tree/badge_bleeding_edge
=> DOC: add a badge to README.rst for bleeding edge CI

unyt/array.py, unyt/tests/test_unyt_array.py
This dtype was apparently overlooked in PR #56
```python
import unyt as u
a = u.unyt_array(1, "cm", dtype="int8")
a.to("km") 
```
fails with
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-fe344d50e9a4> in <module>
1 import unyt as u
2 a = u.unyt_array(1, "cm", dtype="int8")
----> 3 a.in_units("km")
~/dev/python/yt-project/unyt/unyt/array.py in in_units(self, units, equivalence, **kwargs)
845                     )
846             new_dtypekind = "c" if self.dtype.kind == "c" else "f"
--> 847             new_dtype = np.dtype(new_dtypekind + str(dsize))
848             ret = np.asarray(self.ndview * conversion_factor, dtype=new_dtype)
849             if offset: …
```
=> BUG: fix unit conversion for array with dtype int8

unyt/array.py, unyt/tests/test_unyt_array.py
Simple fix to address #230. Replaced `POWER_SIGN_MAPPING` with `POWER_MAPPING` and had this return simple functions (`lambda`s) to compute the exponent instead of just giving the sign of the exponent, which was used in the previous incorrect implementation. Added some unit tests for `np.divide.reduce` (and `np.multiply.reduce` for good measure), these fail before changes and pass afterwards. Also ran `black` and committed the result before starting so I could start with a "clean" set of tests. The functional changes are in the other two commits.
=> Bugfix for `np.divide.reduce`

unyt/array.py, unyt/tests/test_unyt_array.py
This adresses one of the two bugs reported in #224 
~Based on top of #219 for stability, only the last two commits are exclusive to this branch~
edit: rebased on master !
=> BUG: fix an issue where multiplying a 1-element unyt_array would return a unyt_quantity

docs/conf.py, unyt/array.py, unyt/tests/test_unyt_array.py
Fix #241
The issue was that `numpy.ndarray.reshape` accepts an arbitrary number of (integer) positional arguments to represent the shape
The following calls should be equivalent
```python
a.reshape(1, 2)
a.reshpae((1, 2))
```
I added a test case
=> BUG: fix a regression where unyt_array.reshape wasn't wrapping numpy.ndarray.reshape correctly

docs/conf.py, unyt/unit_object.py, unyt/unit_registry.py
This is an answer to #27. I shave off about 33% of unyt's import time by making Unit objects copies shallow by default, the one difference with a deep copy being that the attached UnitRegistry is shallow-copied.
Using the benchmark I described in #27, I get the import time from 1.6s to 1.0s on my machine.
I hope that this doesn't have undesirable side effects.
Another aspect that could be considered is that the sheer number of copies that are performed at import time is probably a sign that something else isn't optimized.
=> ENH: optimize import time

HISTORY.rst
When trying to create the release for v2.9.0 and uploading the packages to pypi using twine, I get this error:
```
❯ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Uploading unyt-2.9.0-py2.py3-none-any.whl
100%|█████████████████████████████████████████| 147k/147k [00:01<00:00, 115kB/s]
Error during upload. Retry with the --verbose option for more details.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.
```
Running `twine check` reveals the issue:
```
❯ twine check dist/*
Checking dist/unyt-2.9.0-py2.py3-none-any.whl: FAILED
`long_description` has syntax errors in markup and would not be …
```
=> Change rst directive in HISTORY to avoid twine error

unyt/array.py
This change is a solution to a downstream issue in yt:
https://github.com/yt-project/yt/issues/4023
it's a direct follow up to #204 
I'm not 100% sure it's the *right* solution, as I don't understand the original implementation using `__array_func__`, so maybe I'm just missing something, in which case the problem should be resolved on the yt side instead.
@JBorrow I know it's been a little while, any chance you could explain your initial implementation please ?
=> BUG: fix inheritance in unyt_array.__pow__

HISTORY.rst
twine is quite picky about what goes into `long_description`. @neutrinoceros just merge
=> Fix issues with HISTORY for twine

.readthedocs.yaml
This file will be used by readthedocs.org to configure the documentation and will specifically allow us to set the python version used to build the docs.
=> Include .readthedocs.yml

tox.ini
Cleanup. According to the comment I left there, this pin isn't necessary now that support for Python 3.6 was dropped.
=> TST: unpin pytest

unyt/tests/test_dask_arrays.py
=> TST: skip dask tests when dask isn't installed

setup.cfg, unyt/__init__.py, unyt/_mpl_array_converter/__init__.py, unyt/_on_demand_imports.py, unyt/array.py, unyt/mpl_interface.py, unyt/tests/test_dask_arrays.py, unyt/tests/test_mpl_interface.py
This is another step to resolve #27
Overall, this gets us to a state where core dependencies (numpy + sympy) are responsible for at least 50-60 % of unyt's import time.
This refactor is similar to my work in yt https://github.com/yt-project/yt/pull/3935
It allows for optional dependencies to never be imported before they are actually requested by users, reducing unyt's own startup time when heavy optional dependencies are installed.
Making matplotlib a true "on-demand" import took a little more work, but now `import unyt` doesn't cause `matplotlib` to be imported too when available, reducing the startup time by about 15% to 25% with respect to unyt 2.9.2 (on my machine).
=> ENH: implement lazy imports for optional dependencies

tox.ini, unyt/dask_array.py
Right now if you try to run the tests with `pytest --doctest-plus --doctest-modules` when dask isn't installed you will get an error:
```
_____________________ ERROR collecting unyt/dask_array.py ______________________
unyt/dask_array.py:20: in <module>
_dask_Array = dask.array.core.Array
unyt/_on_demand_imports.py:32: in __getattr__
raise self.error
E   ImportError: This functionality requires the dask package to be installed.
```
This is happening because pytest has discovered doctests in `unyt/dask_array.py` but that module imports stuff from dask at top-level so the test discovery is failing. To fix that we need to make those top-level imports have a fallback when dask isn't installed. We also need to tell pytest to skip the doctests in that file. There was code already to handle …
=> restore ability to run tests when dask isn't installed

docs/usage.rst, unyt/array.py, unyt/tests/test_unyt_array.py
Sorry for getting this out on a Friday night, no need to take a look at this immediately.
I noticed that `unyt_quantity.to_string` wasn't being tested, so I modified the `from_string` test to round-trip back to a string via `to_string`. In the process, I noticed that ints weren't being loaded as I expected them to. I think it's probably closer to what a user would naively expect if we don't convert everything to float.
Since this behavior was included in a release it's possible some downstream users are relying on it. That said, I don't immediately see how making this change would cause much breakage since numpy and unyt can mix ints and floats with no issues.
Finally, the regex originally used parses `1.` as `1`, not `1.0` (python parses `1.` as `1.0`). Until making this change that …
=> make unyt_quantity.from_string parse ints

tox.ini
Since the current version of coverage is greater than 5.0, these version constraints are unnecessary.
=> remove unnecessary version constraints for coverage in tox config

setup.py
This fixes a warning setuptools is printing on CI:
```
/tmp/pip-build-env-s0dabqhd/overlay/lib/python3.8/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'unyt._mpl_array_converter' as data is deprecated, please list it in `packages`.
!!
############################
############################
Python recognizes 'unyt._mpl_array_converter' as an importable package,
but it is not listed in the `packages` configuration of setuptools.
'unyt._mpl_array_converter' has been automatically added to the distribution only
because it may contain data files, but this behavior is likely to change
in future versions of setuptools (and therefore is considered deprecated).
Please make sure that 'unyt._mpl_array_converter' is included as a package by using
the …
```
=> fix setuptools warning

unyt/array.py, unyt/dask_array.py, unyt/tests/test_dask_arrays.py, unyt/tests/test_mpl_interface.py, unyt/tests/test_unyt_array.py
This PR improves a few places where we were missing test coverage. There are only two areas where we don't have 100% test coverage after this, both of which are hard to test and I'm OK with not having test coverage there.
The fixes fall into two flavors:
* Removing unnecessary compatibility code for old versions of dependencies we no longer support
* Fixing places where new code that's been added in the past couple years didn't have test coverage, either by removing unnecessary code or fixing existing broken tests.
@chrishavlin one of the changes was to delete `unyt_dask_array.__array_function__` since none of the existing tests invoke that function. Can you confirm that my change is correct and `__array_function__` is never called by code outside of `unyt`? It could also be that the …
=> Improve test coverage

unyt/_array_functions.py, unyt/_deprecation.py, unyt/array.py, unyt/tests/test_array_functions.py, unyt/tests/test_unyt_array.py
My initial motivation here was to add some unit representation to error messages when comparing two unyt_array instance via functions from `numpy.testing`, like so:
```python
import numpy as np
import unyt as un
a = [1, 2, 3] * un.cm
b = [1, 2, 3] * un.km
np.testing.assert_array_equal(a, b)
```
which yields, on master:
```
...
AssertionError:
Arrays are not equal
Mismatched elements: 3 / 3 (100%)
Max absolute difference: 299997.
Max relative difference: 0.99999
x: unyt_array([1, 2, 3])
y: unyt_array([1, 2, 3])
```
and on this branch
<details>
<summary>previous version</summary>
```
...
AssertionError:
Arrays are not equal
Mismatched elements: 3 / 3 (100%)
Max absolute difference: 299997. cm
Max relative difference: 0.99999 dimensionless
x: unyt_array([1, 2, 3] cm)
y: unyt_array([1, 2, 3] …
```
=> ENH: Provisional support for NEP 18 (__array_function__ protocol)

unyt/array.py
in response to #291, now assuming that unyt's next version will be 3.0 because we can't add support for NEP 18 while entertainaing 100% backward compatibility
=> DEPR: mark upcoming deprecations as 'since v3.0'

unyt/_array_functions.py
follow up to #293
Apply rules established in #200:
- the out argument is only valid if it's a unyt_array with an appropriate unit (convertible to the expected return unit)
- if its unit doesn't match the "natural" one (say if we concatenate two arrays with units "cm", but we out to a third array with units "km"), convert it in place
=> ENH: harmonize rules for how NEP 18 functions handle an *out* argument

unyt/_array_functions.py, unyt/array.py, unyt/tests/test_array_functions.py
See https://github.com/yt-project/unyt/issues/289#issuecomment-1279862821 for motivation.  With this PR the script in the comment after that one prints:
```
[[ 6. 12. 18.]
[ 6. 12. 18.]
[ 6. 12. 18.]] g*kg
[[ 6. 12. 18.]
[ 6. 12. 18.]
[ 6. 12. 18.]]
<class 'unyt.array.unyt_array'> <class 'numpy.ndarray'>
[[ 6 12 18]
[ 6 12 18]
[ 6 12 18]] g*kg
[[ 6 12 18]
[ 6 12 18]
[ 6 12 18]]
<class 'unyt.array.unyt_array'> <class 'numpy.ndarray'>
```
(I guess not great that there's still a difference in the result's dtype..)
Happy to add more tests if you want me to.
=> support ndarray as arguments for wrapped functions

unyt/tests/test_array_functions.py
I fixed the the xfail reasons for `np.linalg.pinv` tests with stacks. I will report the issue upstream when this goes in.
=> TST: remove incorrect __array_function__ test (matmul is a ufunc)

unyt/_array_functions.py, unyt/tests/test_array_functions.py
This proposes another change to how we handle `out` arguments, again to make the behavior more similar to the current behavior of ufuncs. To illustrate this, take a look at the following script:
```
In [1]: import unyt as u
In [2]: import numpy as np
In [3]: a = [1, 2, 3]*u.g
In [4]: b = [1, 2, 3]*u.kg
In [5]: c = np.zeros((3, 3))*u.W
In [6]: np.add(a, b, out=c)
Out[6]: 
unyt_array([[1001., 2002., 3003.],
[1001., 2002., 3003.],
[1001., 2002., 3003.]], 'g')
In [7]: print(c)
[[1001. 2002. 3003.]
[1001. 2002. 3003.]
[1001. 2002. 3003.]] g
```
From which we see that ufuncs overwrite the output units.
IMO this is preferable to the current behavior for e.g. np.dot, which will check if `out` has units, raise an error if the units aren't convertible, and convert the result to `out`'s units …
=> make array functions with out arguments behave more similarly to ufuncs

unyt/_array_functions.py, unyt/tests/test_array_functions.py
fixes the broken test I pointed to in #307 (but doesn't adresses the core issue)
=> TST: simplify units comparison in tests

pyproject.toml, unyt/_array_functions.py, unyt/tests/test_array_functions.py
- fix #311
- fix another instability where a new (hidden) function `numpy._no_nep50_warning` wasn't whitelisted from NEP 19 completeness tests
I'm ran the bleeding-edge workflow on my fork to demonstrate that this works:
https://github.com/neutrinoceros/unyt/actions/runs/3360690325
While I'm at it I also switched on color logs for pytest, which I think make logs on GH more readable.
=> BUG: (NEP 18) fix upstream instabilities

unyt/_array_functions.py, unyt/tests/test_array_functions.py
another batch of NEP 18 functions
=>  ENH: (NEP 18) implement np.isclose, np.allclose, np.*space and np.copyto + additional tests for noop implementations

pyproject.toml, tox.ini, unyt/_array_functions.py, unyt/tests/test_array_functions.py
for context, see discussion in #289, starting in https://github.com/yt-project/unyt/issues/289#issuecomment-1314196723
opening as a draft because it will inevitably conflict with #324
=> ENH: (NEP 18) implement numpy.savetxt

pyproject.toml
context: explictly declaring `wheel` as a build-time dependency is not needed with `pip>=19.0`, and the oldest supported Python version is now 3.8.0, which ships with `pip==19.3.2`
=>  BLD: remove wheel from explicit build time requirements (not needed in Python>=3.8)

.github/workflows/ci.yml
This PR isn't meant to be merged. Rather, I intend to use it as a playground to discover bugs with the upcoming new major release of tox. Best case scenario nothing breaks and we can close this.
=> TST: pin tox<4.0 to workaround incompatibility with tox-pyenv

unyt/tests/test_unyt_array.py
Follow up to #333, fix a test that fails with the newly released version of numpy (1.24)
=> TST: fix a test to work on numpy 1.24

unyt/_array_functions.py, unyt/exceptions.py, unyt/tests/test_array_functions.py
`cumprod` is a bit tricky, I don't think there's a *right* way to handle it, so I'm just adding a warning to raise awareness
=> ENH: (NEP 18) implement and test cumulative functions

unyt/array.py
Calling `isinstance(i1, _dask.array.core.Array)` leads to importing dask if it's installed but not yet imported, but if it's not imported well, we don't need to check if i1 is a dask Array.
Changing this check to be more clever avoids forcing the import of dask (about as expensive as numpy) on `import yt.utilities.physical_constants` and avoids bloating yt's startup time.
=> ENH: avoid importing dask when possible

.github/workflows/ci.yml, CONTRIBUTING.rst, tox.ini
Since tox-pyenv looks unmaintained (no response from the maintainer in 3 weeks now), let's experiment with a candidate replacement.
Because this makes tox 4 usable in CI for the first time, this may require some tweaks.
I'd also need to make changes in the dev guide if this works.
=> TST: migrate from tox-pyenv to tox-gh-actions

tox.ini
`setuptool_scm` is only a dependency at buildtime and is already specified in `pyproject.toml` so we don't need it in `tox.ini`
=> TST: cleanup redundant requirements in tox.ini

unyt/_array_functions.py, unyt/testing.py, unyt/tests/test_array_functions.py, unyt/tests/test_unyt_array.py
Covers most of the functions last disscussed in https://github.com/yt-project/unyt/issues/289#issuecomment-1369294217
=> ENH: (NEP 18) test and implement combinatory functions

unyt/dask_array.py
`unyt.dask_array` itself isn't loaded with `import unyt` so this doesn't make `dask` a hard dependency to the whole package, just the one module that is already unusable without it.
I find this simple change helps with boostrapping type-checking in unyt (see #296) because `mypy` is (rightfully) confused by conditional inheritance as is currently implemented in `unyt_dask_array`.
Namely, this resolves the following warnings from mypy
```
unyt/dask_array.py:194: error: Variable "unyt.dask_array._dask_Array" is not valid as a type  [valid-type]
unyt/dask_array.py:194: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
unyt/dask_array.py: note: In class "unyt_dask_array":
unyt/dask_array.py:194: error: Invalid base class "_dask_Array"  [misc]
``` …
=> ENH: make dask a hard requirement for unyt.dask_array

docs/usage.rst, unyt/_physical_ratios.py, unyt/_unit_lookup_table.py
This PR introduces several other common values for the solar metallicity found in the literature as new metallicity units, e.g. `"Zsun_angr"`, etc. 
The default mass fraction in `"Zsun"` is still the one from Cloudy and has not been touched. 
Explanatory documentation has been added.
=> Additional metallicity mass fraction conversions

.github/workflows/ci.yml, tox.ini
Note that Python 3.11 is not yet available via pyenv, so I'm not updating dev docs for now.
=> TST: add Python 3.11 to test matrix

.pre-commit-config.yaml, pyproject.toml, setup.cfg, unyt/_array_functions.py, unyt/array.py, unyt/exceptions.py, unyt/unit_object.py
Ruff reimplements a bunch of linters that we're already using in rust. The performance gain is nice but somewhat anecdotal for unyt.
The main reasons I'd like to propose this migration are:
- align unyt with other projects in the org (mainly yt)
- reduce the number of linting dependencies that we need to keep track of
- I just found 2 bugs (unreleased) with it (could have caught them with `flake8-bugbear` had it been up to date)
=> STY: migrate linting to ruff

.github/dependabot.yml
automate workflow updates with dependabot.
see https://github.com/yt-project/yt/issues/4333 for why this is needed
=> MNT: enable dependabot autoupdates for GitHub workflows

HISTORY.rst, unyt/array.py, unyt/tests/test_unyt_array.py
backports #371
This was discussed with @ngoldbaum in the aforementioned PR, but given how fast this move has been, I will wait for an explicit approval before moving this forward.
(in particular: ping @jzuhone)
=> REL: prepare release 2.9.5

CONTRIBUTING.rst
discovered this while working on the 2.9.5 release
=> DOC: add missing step to release guide (install pytest)

unyt/exceptions.py
fix a non-fatal formatting error I made in b666fc60
=> BUG: fix string formatting in UnitOperationError

unyt/testing.py
`import numpy.testing` adds about 4% overhead to unyt's startup time.
measured and visualised with the following command
```
python -X importtime -c "import unyt" 2> import.log && tuna import.log
```
=> ENH: avoid importing numpy.testing at startup

.pre-commit-config.yaml, pyproject.toml
black recently gained the ability to infer minimal target versions from project metadata (`[project]:requires-python`) (see https://black.readthedocs.io/en/stable/change_log.html#id2)
as did `ruff` (see https://github.com/charliermarsh/ruff/pull/3470)
I'm also cleaning up `black`'s `line-length` option since its set to the default value.
=> MNT: clean redundant minimal supported version metadata

unyt/_array_functions.py, unyt/tests/test_array_functions.py
=> ENH: (NEP 18) implement and test np.in1d and np.interp

unyt/_array_functions.py, unyt/array.py, unyt/tests/test_array_functions.py
Taking care of `np._ix` and going down the rabbit hole in `astropy`, found about this rule in NEP 18 that unsupported functions should yield a `NotImplemented` sentinel value (which _then_ triggers a `TypeError`).
=> ENH: (NEP 18) follow NEP 18 more closely for unsupported functions

unyt/_array_functions.py, unyt/tests/test_array_functions.py
closes #289
full disclosure: I still have very little idea what `np.linalg.svd` does, supposedly this follows how astropy implements it.
=> ENH: (NEP 18) implement and test np.linalg.svd

CONTRIBUTING.rst, pyproject.toml, tox.ini, unyt/tests/test_array_functions.py
As discussed in #401
Also added a missing mention of dask in the dev guide that I stumbled upon while scanning for dependencies.
=> Drop support for numpy<1.19

unyt/array.py, unyt/dask_array.py, unyt/tests/test_unyt_array.py
This is the only long standing deprecation that I found.
While I'm at it, I'm made `bypass_validation` and `name` keyword-only arguments, and updated docstrings
=> DEPR: expire deprecation for input_units argument

unyt/array.py
I initially planned this deprecation in #200 but while trying to activate it (#404), I realized that `np.testing.assert_allclose` could not be used as a drop in replacement, so let's just remove this TODO comment.
=> MNT: cleanup dead deprecation message

unyt/array.py, unyt/tests/test_unyt_array.py
Had to repeat the logic of the conditional to avoid changing the signature of `_preserve_units` (in order to include the ufunc, required for `UnitOperationError`). Happy to revise it if anyone sees a better way.
=> DEPR: expire deprecation for mixed temperature units in ufuncs

docs/usage.rst, unyt/array.py, unyt/tests/test_units.py, unyt/unit_object.py
This resolves the first problem in #407
It seems to break other tests (nothing that seems unfixable though), so I thought I'd expose early in case anyone wants to provide feedback
=> BUG: fix unit comparison for K VS degC

unyt/array.py, unyt/tests/test_unyt_array.py
=> BUG: fix converting a dimensionless array with unyt_array.to_astropy

docs/usage.rst, unyt/dimensions.py, unyt/tests/test_unyt_testing.py
Extend the `@returns` decorator so it can handle functions with multiple return values.
Example:
```python
>>> @returns(length, length/time**2)
... def f(a, v):
...     return a * v, v / a
...
>>> res = f(a= 2 * u.s, v = 3 * u.m/u.s)
>>> print(*res)
6 m 1.5 m/s**2
```
I think I've followed everything in [CONTRIBUTING](https://github.com/yt-project/unyt/blob/main/CONTRIBUTING.rst), but please let me know if I've missed anything.
=> Allow dimension-checking of multiple return values

docs/usage.rst, unyt/_array_functions.py, unyt/array.py, unyt/tests/test_array_functions.py
=> BUG: (NEP 19) fix array repr compatibility with Numpy 2.0

pyproject.toml, tox.ini, unyt/_array_functions.py, unyt/tests/test_array_functions.py
Fix a new incompatibility with numpy's dev branch (see https://github.com/numpy/numpy/pull/24376)
This bug only affects unyt 3.0, and the fix doesn't need a backport.
=> BUG: fix an incompatibility with numpy 2.0 (np.asfarray is removed)

unyt/_array_functions.py
A minor memory-management optimization: `unyt_array.to(units).value` makes two copies, `unyt_array.to_value(units)` only makes one.
=> ENH: avoid unnecessary copies in np.historgram* functions

unyt/tests/test_unyt_array.py
There's a new incompatibility where a Unit object that was pickled with sympy 1.8 doesn't compare correctly with the same object generated with sympy 1.12. Unfortunately this case wasn't sufficiently tested so it was discovered _after_ sympy 1.12 was released, within yt test infrastructure.
This adds completes the regression test.
I'll report the issue upstream later today. I've identified the first broken commit as https://github.com/sympy/sympy/commit/40f0f6cfa2af216247476d3f416c715fefde6335
=> TST: add test for new regression with sympy 1.12

unyt/tests/test_array_functions.py
https://github.com/numpy/numpy/pull/24477 broke CI by removing `np.round_`, but in fact we hadn't systematically marked deprecations from numpy 1.25 so this fixes that.
=> TST: fix testability against numpy 2.0 dev (handle numpy 1.25 deprecations)

unyt/_array_functions.py, unyt/tests/test_array_functions.py
Following https://github.com/numpy/numpy/pull/24445
=> BUG: fix an incompatibility with numpy 2.0 (np.trapz and np.in2d are deprecated)

pyproject.toml
fix a new instability in CI caused by the release of matplotlib 3.8.0 yesterday
=> TST: filter a new warning in maptlotlib 3.8 when testing docs in non-interactive agg backend

.github/workflows/bleeding-edge.yaml
At the moment, bleeding edge CI picks up matplotlib nightlies, but this results in downgrading numpy to a stable release (see https://github.com/matplotlib/matplotlib/issues/26847#issuecomment-1729927820)
matplotlib is not a hard dependency to unyt, and we're just using it to test the stability of integrations, but numpy is an absolute core dependency, so I think there's more value in trying to catch incompatibilities with it than with matplotlib.
This patch proposes to limit nightlies tests to core dependencies.
=> TST: unlock numpy 2.0 on bleeding-edge CI

docs/extensions/show_all_units.py, pyproject.toml, unyt/_unit_lookup_table.py, unyt/unit_registry.py
follow up to #367
context:
Following [gist.github.com/aureliojargas/70bd3667afd18f2a4f4e23d7ae5a2915](https://gist.github.com/aureliojargas/70bd3667afd18f2a4f4e23d7ae5a2915):
Comprehension-related autofixes are not included in ruff's UP (pyupgrade) rule set because they are redundant with a subset of flake8-comprehensions. Here I'm choosing to activate the whole set of rules from this plugin for simplicity of configuration.
=> STY: activate flake8-comprehensions (ruff)

unyt/tests/test_array_functions.py
fix nightly tests, following the addition of 2 new NEP18-wrappable functions (see https://github.com/numpy/numpy/pull/24887)
=> ENH: (NEP 18) add tests for new functions in numpy.linalg

unyt/array.py
fix an on-going failure in bleeding-edge CI
Context:
https://github.com/numpy/numpy/pull/24634
The comment I'm removing is from https://github.com/yt-project/unyt/pull/204. Local testing suggests that it's not necessary anymore (tests introduced in the same PR still pass), I suspect this is due to bumping our minimal requirements for numpy since that PR.
Opening as a draft for validation against the full CI. If all goes well, I'll try to remove `unyt_array.__pow__` completely
=> BUG: fix future incompatibility with numpy 2.0 (numpy.core isn't public API)

unyt/tests/test_array_functions.py
This fixes tests with bleeding-edge numpy. I'm relatively confident this is the correct fix, but I want to come back to it later when I have more time to double check, so, opening as a draft for now.
=> TST: adapt a test to numpy 2.0 (NEP 50)

unyt/tests/test_array_functions.py
context: https://github.com/numpy/numpy/pull/24818
=> TST: refactor test for numpy.cross following new deprecation in numpy 2.0

docs/usage.rst, unyt/__init__.py, unyt/_unit_lookup_table.py, unyt/tests/test_no_duplicates.py
This PR handles duplicate symbols from `unit_symbols` (`Unit` objects) and `physical_constants` (`unyt_quantity` objects) in the `unyt` top-level namespace.
* It removes `amu` as a physical constant, since it is typically used as a unit of measure.
* For all other duplicates in the top-level namespace, physical constants are what will be exposed. 
* Documents the fact that duplicates in the top-level namespace defer to physical constants.
Resolves Issue https://github.com/yt-project/unyt/issues/440.
=> Handle duplicate symbols in the unyt top-level namespace

.github/workflows/ci.yml, pyproject.toml, tox.ini
With the release of h5py 3.10.0 (including cp312 wheels), I expect this to be possible. If there are any unexpected blockers we should be able to catch them in CI
=> TST: add CPython 3.12 to test matrix

.github/workflows/ci.yml, pyproject.toml, tox.ini, unyt/_on_demand_imports.py
This PR drops support for Python 3.8 and updates support for associated packages.
@neutrinoceros when we dropped support for versions 3.6 and 3.7 you came up with a list of minimal versions for other packages--how did you do that?
=> Drop python 3.8 support, update package support

unyt/_array_functions.py, unyt/tests/test_array_functions.py
=> BUG: fix backward compatibility for calling np.histogram with implicit range units

unyt/_array_functions.py, unyt/tests/test_array_functions.py
Address the first part of #462
=> BUG: fix an issue where array functions would raise UnitConsistencyError on unyt arrays using non-default unit registries

tox.ini
Just learned that tox 4 allows universal wheels to be built once and reused across multiple envs, reducing the build time to a minimum.
https://tox.wiki/en/latest/upgrading.html#universal-wheels
=> TST: minimize build time in tox runs

unyt/_array_functions.py, unyt/tests/test_array_functions.py
based on #463, closes #462 
this patch was semi-automated with the following script:
```python
import re
from pathlib import Path
module_file = Path(__file__).parent / "unyt" / "_array_functions.py"
module_file.write_text(
re.sub(
r"(?P<varname>[\w_]+)\.view\(np.ndarray\)",
lambda match: f"np.asarray({match.group('varname')})",
module_file.read_text(),
)
)
```
=> BUG: fix an issue where array functions would crash (AttributeError) when passed non-ndarray array like objects (e.g. Python lists)

CONTRIBUTING.rst
- recent versions of pyenv allow the micro Python version to be left unspecified, which is probably better style
- also follow up to #460 and only recommend installing supported versions
=> DOC: update pyenv commands in docs

docs/usage.rst, unyt/tests/test_unit_registry.py, unyt/unit_registry.py
=> BUG: explicitly forbid destructive edits to the default unit registry

unyt/tests/test_unyt_array.py
Now that unyt requires numpy>=1.19.3, there's no need for this decorator.
=> TST: cleanup an unused skip condition

pyproject.toml, unyt/tests/test_array_functions.py, unyt/tests/test_mpl_interface.py
Lint numpy specific rules with ruff and manually fix deprecated `numpy.random` API usage
=> TST: fix usage of legacy numpy.random API in tests

unyt/_array_functions.py, unyt/testing.py, unyt/tests/test_array_functions.py
Replaces #482, also fixes #481 (even including API that were introduced after #482)
=> (NEP 18) Implement and test array functions new in numpy 2.0

unyt/tests/test_unit_registry.py, unyt/unit_registry.py
=> BUG: fix caching error with UnitRegistry.modify

pyproject.toml
example log: https://github.com/yt-project/unyt/actions/runs/8026589357/job/21929335189
the problem is already adressed upstream in https://github.com/sympy/sympy/pull/25290, so no further report is needed
=> TST: filter a deprecation warning from mpmath triggered by sympy

.github/workflows/bleeding-edge.yaml
Turns out #489 wasn't sufficient to fix bleeding-edge CI. [Example log](https://github.com/yt-project/unyt/actions/runs/8034078442)
So I dug a little deeper and what's happening is that `mpmath` (which we depend on indirectly via `sympy`) is preparing a new release, [currently in alpha (1.4.0a0)](https://pypi.org/project/mpmath/1.4.0a0/), which breaks `sympy`. It's all being discussed upstream by their respective maintainers (see https://github.com/sympy/sympy/issues/26268 and https://github.com/mpmath/mpmath/issues/704), so there isn't much we can do about it on our side but hope for the best outcome.
While we still want to test against sympy pre-releases, we should probably not care about testing with pre-releases of *its* dependencies (they are doing it already). The way to do that …
=> TST: avoid installing mpmath pre-releases in bleeding edge CI

unyt/array.py
In numpy 2.0, passing `copy=False` to `np.array` raises an error if copying cannot be avoided.
xref https://github.com/astropy/astropy/pull/16142
=> BUG: fix compatibility with numpy 2.0 copy semantics

.github/workflows/ci.yml
Context: [`macos-latest` is being migrated repo-by-repo from `macos-12` (x86) to `macos-14` (arm64)](https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/)
It appears that this migration was rolled out for unyt 3 days ago. As a result, regular CI is broken on macOS+py39, presumably because of a faulty docker image. No test is failing, but jobs are still reported as failed. Pinning to an 'old' macOS image seems appropriate here and fixes the immediate problem.
=> MNT: use macOS x86 for Python 3.9 in CI

docs/usage.rst, tox.ini, unyt/array.py
A couple non-user facing adjustments to numpy 2.0
[example logs](https://github.com/yt-project/unyt/actions/runs/9540016330/job/26291141524)
=> DOC: adjust doctests to changes in array repr from numpy 2.0

docs/usage.rst, unyt/_array_functions.py, unyt/tests/test_array_functions.py
- **BUG: test/implement array functions new in NumPy 2.1 (np.cumulative_sum and np.cumulative_prod)**
- **BUG: adapt np.clip's implementation signature at runtime**
[example logs](https://github.com/yt-project/unyt/actions/runs/9774860392/job/26984040518)
xref: https://github.com/numpy/numpy/pull/26724
=> BUG: fix incompatibilities with NumPy 2.1

unyt/_physical_ratios.py, unyt/_unit_lookup_table.py
these are used in supernovae
see: https://en.wikipedia.org/wiki/Foe_(unit)
=> add foe and Bethe units

.github/workflows/bleeding-edge.yaml
~Currently based off #504 and #506~
=> TST: switch bleeding-edge CI to CPython 3.13

.github/workflows/ci.yml
Following the upcoming deprecation of this runner image https://github.com/actions/runner-images/issues/10721
=> MNT: switch Python 3.9 + mac testing from macos-12 to macos-13

.pre-commit-config.yaml, unyt/_array_functions.py
- one less hook
- almost no difference in results
- faster formatting
=> STY: migrate formatting from black to ruff

unyt/_array_functions.py, unyt/tests/test_array_functions.py
Closes #538 
When `weights` are given to a histogram function the histogram should inherit the units of the weights. When `density=True` is set, the histogram should have the inverse units of each dimension of the input applied.
=> BUG: `np.histogram*` functions give correct units when `weights` and/or `density` are set

unyt/_array_functions.py, unyt/tests/test_array_functions.py
The implementations of `linspace` and `logspace` are improved so that `retstep` can be used with `linspace` and `logspace` rejects inputs for `start` and `stop` with non-dimensionless units, and also correctly handles the `base` keyword argument with units.
Tests are updated to reflect changes.
Closes #542
Closes #543
=> BUG: `linspace` and `logspace` give incorrect results or crash with some inputs

unyt/_array_functions.py, unyt/tests/test_array_functions.py
Previously the numpy function `apply_over_axes` assumed that the first argument, a user-supplied function, returned values with the same units as the input, which could give incorrect output (e.g. for a function `lambda x, axis: x ** 2`). It's beyond the scope and ability of `unyt` to strictly enforce consistency here, but the updated function now allows units to propagate naturally through the supplied function.
Closes #545
=> BUG: `apply_over_axes` no longer assumes user-supplied function preserves units

unyt/array.py
This is a one-line change to enable subclasses of `unyt_quantity` to work properly, otherwise the subclass will not recognize itself as being a `unyt_quantity` and the logic breaks.
=> BUG: allow subclassing in `unyt_array.__array_func__`

unyt/_array_functions.py, unyt/array.py, unyt/tests/test_array_functions.py
Closes #549
Wasn't quite sure where to put some bits of this so might make sense to move things around a bit.
=> BUG: fix unit handling for `np.take` and `unyt_array.take`

unyt/_array_functions.py
This fixes a regression I overlooked when reviewing #544 but poped up in yt's test suite https://github.com/yt-project/yt/issues/5091
for posterity: this regression never landed in a release.
=> BUG: fix a regression where `np.linspace`'s num argument would be ignored for `unyt_array`s

unyt/array.py, unyt/tests/test_array_functions.py
In the tests of array functions, one of the tested functions `np.vecdot` is actually a ufunc. I'm relying on the set of `NOOP_FUNCTIONS` in an in-development addition to the https://github.com/SWIFTSIM/swiftsimio test suite to check that our code at least supports all numpy functions supported by unyt, and having a (single) ufunc in the list breaks things. I'm therefore proposing to remove it from the list here. I've also removed the test of the function, perhaps it should be migrated to `test_unyt_array.py`, but I can't spot an obvious place to put it.
Note that `np.linalg.vecdot` *is* an array function, not a ufunc.
=> RFC: handle `np.vecdot` as a ufunc rather than an arrayfunc

unyt/array.py, unyt/tests/test_unyt_array.py
Trying to fix the few cases where it *does* make sense to raise a unyt array to a power array.
Close #522
=> BUG: fix raising a unyt array to an array power in sensible cases

.github/workflows/ci.yml, tox.ini
blocked by:
- https://github.com/hgrecco/pint/issues/1969
=> TST: add CPython 3.13 to regular test matrix

.github/workflows/publish.yml, CONTRIBUTING.rst
=> REL: automate release upload to PyPI

unyt/tests/test_array_functions.py
Close #564
See https://github.com/numpy/numpy/issues/28493#issuecomment-2721303048
=> TST: make `test_unique_values` order-agnostic and fix testing against numpy 2.3 dev

unyt/_array_functions.py
I realised that in [swiftsimio](https://github.com/SWIFTSIM/swiftsimio) we wanted to support `__mul__` and similar methods on our array class. This revealed that the implementation of `np.block` in unyt attaches units to the result by multiplying them on, which results in a partially initialised object calling `__mul__` on our side when we wrap `np.block`. This PR changes the wrapper for `np.block` to attach units using the `unyt_array` constructor, in line with other similar helper functions.
=> Don't use multiplication to attach units to result.

pyproject.toml, tox.ini
This is the fundamental piece from #532. I've stripped out the (partially broken) changes to CI, but this is already useful on it's own: it allows running the test suite with `uv run --group test pytest unyt` instead of a `tox` command.
=> DEP: declare test dependencies as PEP 735 dependency groups

MANIFEST.in, pyproject.toml
`project.license` is deprecated as a TOML table since `setuptools` `77.0.0`:
https://setuptools.pypa.io/en/latest/history.html#id73
I adjusted for this change using the now prefered standard, [PEP 639](https://peps.python.org/pep-0639/#deprecate-license-key-table-subkeys), which also mentions the `License :: OSI Approved :: BSD License` classifier being ambiguous, and as such, leads to an error in `setuptools` if present, because it would override PEP 639 definitions, so I removed it.
Setuptools also auto-includes files listed in `project.license-files`, so we don't need to explicitly ask for it in `MANIFEST.in`
While I was at it, I noticed we were missing an obvious `Intended Audience` trove classifier, so I added it.
=> MNT: adjust license spec to PEP 639
