yt-project/unyt

docs/usage.rst
Leaving this open in case anyone wants to take a look at it.
Going to start drafting the paper now. The paper will include the performance comparison.
=> Finish the docs

README.rst
I thought it might be helpful to note that there aren't any dependencies that are too heavy -- especially yt itself.
=> Make lack of dependencies a bit clearer

unyt/_unit_lookup_table.py
=> add smoot, closes #13

.travis.yml, tox.ini
This should hopefully unbreak the tests on MacOS.
=> use pyenv to set up test environment

unyt/unit_symbols.py
=> fix definition of Megagram

tox.ini, unyt/__init__.py
=> Add numpy and sympy import checks to top-level __init__.py

LICENSE
=> Update LICENSE so github recognises

unyt/unit_symbols.py
=> add microsecond to unyt namespace

HISTORY.rst, docs/usage.rst, unyt/tests/test_unit_systems.py, unyt/unit_registry.py, unyt/unit_systems.py
ping @JBorrow
It looks like this may have used to work by accident. However it seems like a natural thing to want to do so I've explicitly added support for it, including docs and tests.
=> make sure unit systems can be defined using unit objects. fixes #71

docs/usage.rst, unyt/tests/test_unit_systems.py, unyt/unit_systems.py
This addresses the crash @jborrow described in the comments on #72.
=> allow defining unit systems with a quantity

docs/usage.rst, unyt/__init__.py, unyt/dimensions.py
This PR adds a decorator for checking units of function arguments, as discussed in https://github.com/yt-project/unyt/issues/91.
=> Unit check decorator

tox.ini, unyt/array.py, unyt/tests/test_unyt_array.py
This should probably get backported to yt.units, ping @matthewturk.
=> add support for the clip ufunc and add testing for np.clip, closes #101

.travis.yml
see https://github.com/codecov/codecov-python/issues/224
=> fix codecov integration issue 

unyt/array.py, unyt/tests/test_unyt_array.py
=> coerce data to the destination dtype before multiplying by any converion factors

CONTRIBUTING.rst
ping @l-johnston, let me know if this looks helpful
=> update contribution guide to include pyenv setup

unyt/tests/test_units.py, unyt/tests/test_unyt_array.py, unyt/unit_object.py
logarithmic quantities only support:
- addition, subtraction
- dimensionless multiplication and division
- raise to power 1.0
=> fix invalid logarithmic unit operations

unyt/dimensions.py
fixes #146 by changing behaviro of _has_dimensions: non-quantity values are assumed to be dimensionless
=> Fix for #146 (Checking units/dimension of dimensionless quantities)

unyt/_unit_lookup_table.py, unyt/tests/test_units.py
Fixes https://github.com/yt-project/yt/issues/2704.
Added a test too.
=> add more alternative spellings for solar units

docs/usage.rst, unyt/_unit_lookup_table.py, unyt/array.py, unyt/tests/test_units.py, unyt/tests/test_unyt_array.py, unyt/unit_object.py
=> Add temperature units delta_degC and delta_degF

unyt/_unit_lookup_table.py, unyt/tests/test_unyt_array.py
The mil, 0.001 inch, is in common use here in the U.S. for printed circuit board design and production.
=> Add the imperial unit mil.

unyt/tests/test_units.py, unyt/unit_object.py
=> Fix SI prefix scaling of degree Celsius

.github/workflows/build-test.yaml
This pull request implements github actions.
The errors that are showing up need to be fixed, which I will do in a separate PR.  Before this goes in, the travis and appveyor configurations should be removed.  Additionally, this should probably be squashed when it goes in.
=> Utilize github actions

unyt/array.py, unyt/tests/test_unyt_array.py
=> Fix unyt_array.__getitem__ to support numpy masked arrays

.github/workflows/bleeding-edge.yaml, .github/workflows/ci.yml
=> TST: run daily CI job against dev branches of matplotlib and numpy

unyt/_unit_lookup_table.py
=> BUG: fix typos in constants

unyt/_physical_ratios.py, unyt/_unit_lookup_table.py, unyt/dimensions.py
This PR:
* Adds the dimension `angular_frequency` and the unit `rpm`.
* Adds the [Rydberg constant and Rydberg unit](https://en.wikipedia.org/wiki/Rydberg_constant).
* Removes the hard-coded value of the `elementary_charge` in two places and puts it in a variable in `physical_ratios`.
* Updates the value of Avogadro's number (closes Issue #226)
=> various additions to constants and units

.github/workflows/ci.yml, docs/conf.py, setup.py, tox.ini
Also expanding the github actions tests to exercise all of the tox testing environments.
=> drop python 3.6 and 3.7 support

.github/workflows/bleeding-edge.yaml
This should be trivial (yet kiwisolver is currently a blocker, to be resolved in the coming days)
Opening early to see if there are any unforseen blockers
=> TST: start testing on Python 3.11

setup.py
=> MNT: explicitly declare unyt/tests as a package to be included in dist

HISTORY.rst
@neutrinoceros I missed a few more, please approve and merge
=> Missed doctest directives in HISTORY.rst

.git-blame-ignore-revs, .pre-commit-config.yaml, benchmarks/bench.py, docs/conf.py, docs/extensions/show_all_units.py, unyt/_parsing.py, unyt/_unit_lookup_table.py, unyt/array.py, unyt/dask_array.py, unyt/dimensions.py, unyt/equivalencies.py, unyt/exceptions.py, unyt/tests/test_units.py, unyt/tests/test_unyt_array.py, unyt/unit_object.py, unyt/unit_registry.py, unyt/unit_symbols.py, unyt/unit_systems.py
Additional (and final) style alignment with yt.
This is low priority, I just add a couple minutes to kill
=> STY: flynt + pyupgrade

.github/workflows/ci.yml
=> remove codecov from github actions config

pyproject.toml, setup.py, tox.ini, unyt/_array_functions.py, unyt/array.py, unyt/exceptions.py, unyt/tests/test_array_functions.py, unyt/tests/test_unyt_array.py
implements https://github.com/yt-project/unyt/issues/289#issuecomment-1274964636
TODO:
=> ENH: implement 8 new NEP 18 functions

unyt/_array_functions.py
follow up to #298, and fixes a couple downstream instabilities in yt (see https://github.com/yt-project/yt/actions/runs/3262262016)
=> ENH: (NEP 18) treat pure ndarrays as dimensionless in validation

unyt/_array_functions.py, unyt/tests/test_array_functions.py
Another fresh supply of NEP 18 tests and implems
=> ENH: (NEP 18) implement numpy.trapz and numpy.sort_complex, add tests for more noop NEP 18 functions

unyt/tests/test_array_functions.py
This shouldn't conflict with #320
=> ENH: (NEP 18) misc noop functions

tox.ini
=> TST: ensure coverage is installed with toml support

unyt/_array_functions.py, unyt/tests/test_array_functions.py
I am leaving out `np.linalg.svd` because it's not clear to me what should be done with it
=> ENH: (NEP 18) implement and test np.linalg namespace

unyt/array.py, unyt/exceptions.py, unyt/tests/test_unyt_array.py
upstream test case from yt, see https://github.com/yt-project/yt/issues/4241
For further context, see https://github.com/numpy/numpy/issues/22744
=> BUG: fix compatibility with numpy 1.25 (future)

HISTORY.rst, pyproject.toml, unyt/array.py, unyt/exceptions.py, unyt/tests/test_unyt_array.py
Backports #333
Additional changes:
- added build-backend specifications to pyproject.toml, mimicking the main branch *but pinning* build time dependencies to guarantee build reproductibility
- updated changelog
=> REL: manual backports for release 2.9.3

HISTORY.rst
cherry-pick the changelog update from #335 back to the main branch
=> REL: update changelog for release 2.9.3

CONTRIBUTING.rst, pyproject.toml
=> DOC: update 'how to deploy' docs

unyt/tests/test_array_functions.py
Following https://github.com/yt-project/unyt/issues/289#issuecomment-1369116384, and in the spirit of `astropy.units`
=> TST: (NEP 18) mark polynomial and IO functions as ignored

LICENSE, unyt/__init__.py, unyt/_mpl_array_converter/__init__.py, unyt/_on_demand_imports.py, unyt/_parsing.py, unyt/_pint_conversions.py, unyt/_unit_lookup_table.py, unyt/array.py, unyt/dimensions.py, unyt/equivalencies.py, unyt/exceptions.py, unyt/mpl_interface.py, unyt/physical_constants.py, unyt/testing.py, unyt/tests/test_unit_registry.py, unyt/tests/test_unit_systems.py, unyt/tests/test_units.py, unyt/tests/test_unyt_array.py, unyt/tests/test_unyt_testing.py, unyt/unit_object.py, unyt/unit_registry.py, unyt/unit_symbols.py, unyt/unit_systems.py
=> MNT: drop copyright headers, update LICENSE

.github/workflows/bleeding-edge.yaml, .github/workflows/ci.yml, README.rst, unyt/tests/test_unyt_array.py
=> TST: correctly test string comparison depending on numpy version

unyt/array.py, unyt/tests/test_unyt_array.py
fix #361
I would like to backport this to the 2.9.x branch and ship it as unyt 2.9.4
=> BUG: multiple fixes for unyt_quantity.from_string

.github/workflows/ci.yml, .pre-commit-config.yaml, CONTRIBUTING.rst, HISTORY.rst, README.rst, docs/usage.rst, tox.ini, unyt/array.py, unyt/tests/test_unyt_array.py
Backports:
- #278
- #344 
- #358
- #362
TODO:
=> REL: prep release 2.9.4

HISTORY.rst
=> DOC: fixup markup in HISTORY.rst

unyt/_array_functions.py, unyt/tests/test_array_functions.py
Follow up to https://github.com/yt-project/unyt/pull/351#discussion_r1061809769
=> ENH: (NEP 18) implement numpy.where

unyt/array.py, unyt/tests/test_unyt_array.py
Fixes #373 
There may be other ways to break things via `__setitem__` but this at least fixes the cases raised in the issue. If anyone spots additional things I should be checking, please let me know.
=> Add `__setitem__` implementation

unyt/_on_demand_imports.py
equivalent to https://github.com/yt-project/yt/pull/4226
see https://github.com/yt-project/yt/issues/4224 for context
=> ENH: don't drop ImportError tracebacks for lazily-loaded optional dependencies

unyt/array.py, unyt/tests/test_unyt_array.py
Apparently yt does this in a few places and I think it makes sense to allow it.
=> check if doing setitem with a dimensionless quantity

HISTORY.rst
pull updates from #372 to the main branch
=> DOC: synchronize history with backport branch

unyt/tests/test_array_functions.py
=> TST: adapt tests to new deprecations in numpy 1.25

unyt/array.py
extracting some hopefully uncontroversial change from #355
=> RFC: import 'clip' from numpy namespace directly

unyt/_array_functions.py, unyt/tests/test_array_functions.py
Another dent into NEP 18 implementation
=> TST: (NEP 18) triage and test a handful noop and trivial functions

tox.ini, unyt/array.py, unyt/tests/test_array_functions.py, unyt/tests/test_unyt_array.py
end goal: fix #220
This is very preliminary, as multiple tests are currently broken, but it's getting late, so I'm opening to get this out of my system for today.
=> BUG: fix subtraction for different dimensionally equivalent units

unyt/exceptions.py
A minor improvement around #346
=> RFC: consistently call parent class' __init__ method in Exception subclasses

docs/usage.rst, unyt/exceptions.py
Resolves another part of #346. What's missing is the documentation (other than docstring).
=> ENH: make all custom exceptions derive from UnytError. Document it

docs/index.rst, docs/installation.rst, docs/usage.rst
I'm doing a once-over of the whole documentation. I am not done yet but I'm opening the PR now so it's easier for me to get back to it later.
=> DOC: first pass in preparation for the 3.0 release

.github/workflows/bleeding-edge.yaml, unyt/tests/test_array_functions.py
=> TST: (NEP 18) auto mark deprecated (pure Python) functions as noop

AUTHORS.rst, CONTRIBUTING.rst, HISTORY.rst, docs/usage.rst
This is a documentation update for version 3.0.0. I added entries to `HISTORY` and `AUTHORS`, as well as fix some rendering issues with the deploying docs.
=> Documentation for v3.0.0

.readthedocs.yaml
Updates readthedocs python and ubuntu versions
=> Update readthedocs python and ubuntuversion used

HISTORY.rst
=> Update history for v3.0.1

pyproject.toml
=> BLD: fix minimal requirement on setuptools_scm

unyt/_array_functions.py, unyt/tests/test_array_functions.py
Adding the test first, will push the fix after CI goes red.
=> BUG: fix an issue where array functions would raise UnitInconsistencyError operands' units differ by some dimensionless factor

unyt/_array_functions.py, unyt/tests/test_array_functions.py
xref https://github.com/numpy/numpy/pull/25738
=> BUG: fix compat with numpy dev for np.trapezoid (previously named np.trapz)

HISTORY.rst, pyproject.toml
@jzuhone I arbitrarily set the release date to tomorrow, please let me know if you need more time to review and I'll edit it !
=> REL: prepare release 3.0.2

pyproject.toml, unyt/tests/test_array_functions.py
=> TST: fix defects when running test suite in isolation from the project's pytest configuration

CONTRIBUTING.rst
=> DOC: cleanup orphan reference to now removed setup.py

unyt/_array_functions.py, unyt/tests/test_array_functions.py
I ported a meta test that I originally wrote for astropy.units, and fixed a bunch of subtle signature incompatibilites it detected.
xref https://github.com/astropy/astropy/pull/15710
=> BUG: fix signature incompatibilities in NEP 18 wrapped functions

unyt/unit_object.py
See https://github.com/sympy/sympy/issues/26684
[example logs](https://github.com/yt-project/unyt/actions/runs/9409495739/job/25919532661)
for additional context: this is the *only* regression I saw in the test suite against sympy 1.13.0rc1
=> BUG: fix an incompatibility with sympy 1.13.0rc1

unyt/_array_functions.py, unyt/tests/test_array_functions.py
=> BUG: fix return units from numpy.ftt functions

.github/workflows/bleeding-edge.yaml
In hindsight, daily testing seems like overkill.
=> TST: reduce bleeding edge testing frequency from daily to weekly

unyt/_array_functions.py, unyt/tests/test_array_functions.py
This should resolve #540
@kyleaoman, can I ask for your review ?
=> BUG: fix an issue where `np.histogramdd` could create infinite recursion on some inputs

unyt/_array_functions.py
=> Fix typo in array function implementations (ftt -> fft)

unyt/array.py, unyt/tests/test_unyt_array.py
=> BUG: fix an issue where hdf5 io wouldn't roundtrip properly for a unyt_quantity object

unyt/_array_functions.py, unyt/_unit_lookup_table.py
spat: https://en.wikipedia.org/wiki/Spat_(angular_unit)
turn, pla: https://en.wikipedia.org/wiki/Turn_(angle)
gradian, gon: https://en.wikipedia.org/wiki/Gradian
=> New angular units

.github/workflows/ci.yml, .readthedocs.yaml, CONTRIBUTING.rst, pyproject.toml, tox.ini, unyt/_deprecation.py
=> DEP: drop support for CPython 3.9
